services:
  trajectfi_db:
    container_name: trajectfi_db
    image: postgres:14
    volumes:
      - trajectfi-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  trajectfi:
    container_name: trajectfi
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/home/trajectfi/src
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    depends_on:
      trajectfi_db:
        condition: service_healthy

volumes:
  trajectfi-db-data:

networks:
  default:
    name: trajectfi